### ISSUE TITLE
How would i implement Mongodb in this Stack

### ISSUE THREAD

**Issue by manuva1** [MarvelousWololo/ssr-react#1]
im new to node and react how would i implement mongodb in this project. Thanks and advanced

**Comment by MarvelousWololo** [comment]
Hi @manuva1, this is a regular Node/Express app so you shouldn't have any problem to follow a tutorial like this [Express Tutorial Part 3: Using a Database](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose).
